from pathlib import Path

class ReadmeBuilder:
    VERSION="1.0.0"

    def build(self, package_name:str, version:str, output:Path):
        text=f"""# {package_name}

Version: {version}

## Description

Generated by AHEDK.

## Installation

Run install.bat

## Files

See manifest.json
"""
        output.write_text(text,encoding="utf-8")
        return output
