from pathlib import Path

class EngineBuilder:
    VERSION = "1.0.0"

    def build(self, engine_name:str, project_root:Path):
        name = engine_name.strip().lower().replace(" ","_")
        engine_dir = project_root / "engines" / name
        engine_dir.mkdir(parents=True, exist_ok=True)

        (engine_dir / "__init__.py").write_text(f'"""{engine_name} package."""\n', encoding="utf-8")

        class_name = engine_name.replace(" ","") + "Engine"
        code = f'''"""
{engine_name} Engine
Generated by AHEDK
"""

class {class_name}:
    VERSION = "1.0.0"

    def status(self):
        return {{"engine":"{engine_name}","status":"ready"}}
'''
        (engine_dir / f"{name}_engine.py").write_text(code, encoding="utf-8")
        return engine_dir
